export const SAVE_PROCESSED_TEXT = "SAVE_PROCESSED_TEXT";

export const SET_FETCHED_TEXTS = "SET_FETCHED_TEXTS";
export const ADD_TEXT = "SAVE_TEXT"; //addText
export const GET_TEXT_BY_ID = "GET_TEXT_BY_ID";

export const PROCESS_TEXT = "PROCESS_TEXT";
export const SAVE_MEANING = "SAVE_MEANING";
export const DELETE_MEANING = "DELETE_MEANING";

export const SET_DEFAULT_WORD_FOR_OCCURRENCE =
  "SET_DEFAULT_WORD_FOR_OCCURRENCE"; //setDefault
export const SET_SELECTED_WORD_FOR_EVERY_OCCURRENCE =
  "SET_SELECTED_WORD_FOR_EVERY_OCCURRENCE"; //setSelectedForEveryOccurrence

export const GET_DATA_FOR_LEARNING = "GET_DATA_FOR_LEARNING";
export const UPDATE_DICTIONARY = "UPDATE_DICTIONARY";
export const UPDATE_OCCURRENCE = "UPDATE_OCCURRENCE";

export const GET_MEANINGS_FOR_WORD = "GET_MEANINGS_FOR_WORD";

export const GET_TEMPLATE_DATA = "GET_TEMPLATE_DATA";
export const SET_PROCESSING_OPTIONS = "SET_PROCESSING_OPTIONS";

export const ADD_USER_OCCURRENCE = "ADD_USER_OCCURRENCE"; //addNewOccurrence
export const DELETE_USER_OCCURRENCE = "DELETE_USER_OCCURRENCE"; //deleteOccurrence
export const TOGGLE_USER_TYPE = "TOGGLE_USER_TYPE";

export const CHANGE_SELECTED_WORD = "CHANGE_SELECTED_WORD";
export const SET_FOUND_OCCURRENCES = "SET_FOUND_OCCURRENCES";

export const TOGGLE_ADDING_WORD = "TOGGLE_ADDING_WORD";

export const SET_TO_ADD_OCCURRENCES = "SET_TO_ADD_OCCURRENCES";

export const DESELECT_INLINE_WORD = "DESELECT_INLINE_WORD";
export const CHANGE_SELECTED_OCCURRENCE = "CHANGE_SELECTED_OCCURRENCE";
export const DESELECT_OCCURRENCE = "DESELECT_OCCURRENCE";

export const DELETE_USER_OCCURRENCES_BY_WORD = "DELETE_USER_OCCURRENCES_BY_WORD";
