export const GET_MEANINGS_BY_WORD = "GET_MEANINGS_BY_WORD";
export const GET_DICTIONARY_BY_WORD_ID = "GET_DICTIONARY_BY_WORD_ID";
export const GET_DICTIONARY_BY_WORD = "GET_DICTIONARY_BY_WORD";
export const ESSENTIAL_WORDS = "ESSENTIAL_WORDS";
export const GET_OCCURRENCE_BY_POSITION = "GET_OCCURRENCE_BY_POSITION";
