export const SET_TEXTS = "SET_TEXTS";
export const ADD_OR_REPLACE_TEXT = "ADD_OR_REPLACE_TEXT";
export const SET_OCCURRENCES = "SET_OCCURRENCES";
export const SET_MEANINGS = "SET_MEANINGS";
export const SET_ESSENTIAL_WORDS = "SET_ESSENTIAL_WORDS";
export const SET_TOKENIZED_TEXT = "SET_TOKENIZED_TEXT";
export const UPDATE_MEANINGS_FOR_WORD = "UPDATE_MEANINGS_FOR_WORD"; //addRelatedWords
export const REPLACE_DICTIONARY_WITH_UPDATED =
  "REPLACE_DICTIONARY_WITH_UPDATED"; //updateDictionaryWord
export const REPLACE_OCCURRENCE_WITH_UPDATED =
  "REPLACE_OCCURRENCE_WITH_UPDATED"; //updateSelectedWord
export const DELETE_LEARN_STATE = "DELETE_LEARN_STATE";
export const DELETE_TEMPLATE_STATE = "DELETE_TEMPLATE_STATE";
export const SET_DICTIONARY = "SET_DICTIONARY";

export const DELETE_TOKENIZED_CONTENT = "DELETE_TOKENIZED_CONTENT"; //resetTokenizedContent
export const SET_CURRENT_TEXT = "SET_CURRENT_TEXT";
export const ADD_MEANING_FOR_WORD = "ADD_MEANING_FOR_WORD";
export const DELETE_MEANING_FOR_WORD = "DELETE_MEANING_FOR_WORD";
export const SET_DEFAULT_WORD_FOR_OCCURRENCES =
  "SET_DEFAULT_WORD_FOR_OCCURRENCES"; //setDefaultOccurrences
export const SET_WORD_FOR_SIMILAR_OCCURRENCES =
  "SET_WORD_FOR_SIMILAR_OCCURRENCES"; //setSelectedForEveryOccurrence
export const SET_ONLY_EXCLUSIVE = "SET_ONLY_EXCLUSIVE";
export const ADD_ERROR = "ADD_ERROR";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const TOGGLE_USER_TYPE = "TOGGLE_USER_TYPE";
